[package]
authors = ["crispto <2273713147@qq.com>"]
edition = "2018"
name = "rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.7.7"
log = "0.4"
